### ISSUE TITLE
SONAME Bump

### ISSUE THREAD

**Issue by gftg85** [open-power-sdk/pveclib#109]
Hi, @munroesj52,

I noticed that you bumped libpvec's SONAME to 1:

https://github.com/open-power-sdk/pveclib/blob/3f69c666ac7d703fac6b95ee769c52d45c4221f4/configure.ac#L19

I believe you did it due to the removal of `tifrexpof10` and `tipowof10` by commit ID d49068a3a0bb, even though the SONAME bump happened a couple of commits earlier, i.e. on commit ID b88ec162c2e7. 

My question is... Were the tables wrong? Aren't they worth saving for the sake of backwards compatibility? Or is libpvec such a new library that a SONAME bump won't hurt?

Cheers,
Gabriel

**Comment by munroesj52** [comment]
Actually the Sonam bump is due to the addition of vec_int512_ppc.h and the
ifunc binding. Removing the const array was forced by clang. Clang does
handle int128 const like gcc. For vector I can use vector unsigned long
long int. Then cast to vector __int128. Can't do that for scalar int128 in
clang. What I removed was duplicate int128 scalar array of the vector
int128 array. So I need the alias the scalar to the vector.

**Comment by gftg85** [comment]
I don't understand why ifuncs (or new functions) would require a soname bump, but I get that the tables needed to go away, and that certainly does require the bump.

Thanks for the clarification, Steve.
